name: CI for soft-posit-cpp

on:
  push:
    branches: [ "main", "refactor-cpp-soft-posits" ]
  pull_request:
    branches: [ "main", "refactor-cpp-soft-posits" ]

jobs:
  setup:
    uses: ./.github/workflows/shared-setup.yml
    with:
      build_type: Release
      build_tests: true
      build_benchmarks: true
      cache_key: 'global-release-${{ github.sha }}'
  
  build:
    needs: setup
    uses: ./.github/workflows/shared-build.yml
    with:
      build_type: Release
      build_dir: build
      run_tests: true
      run_benchmarks: true
      cache_key: 'global-release-${{ github.sha }}'
